var myString, newString;
var myNum;
var myBoolean;
var myVar;
var strArr;
var numArr;
var boolArr;
//Other ways of declaring arrays
var stringArr;
var numberArr;
//Tuple declaration
var strNumTuple;
var numStrTuple;
var boolNumTuple;
//play with null void undefined
var myVoid = null;
var myNull = undefined;
var myUndefined = null;
myString = "Hello" + " Modern " + "Typescript";
newString = "Name".slice(1, 2);
myNum = 22;
myBoolean = false;
myVar = true;
strArr = ["Name", "Number", "Address"];
numArr = [1, 2, 3, 4, 5, 6];
boolArr = [true, false];
stringArr = ["My", "Name", "is", "Anish"];
numberArr = [1, 2, 3, 4, 5, 6, 7, 8];
strNumTuple = ["hello", 34];
numStrTuple = [12, "my Number"];
boolNumTuple = [true, 21, 2, 3, 4, 5, 6, 7];
console.log(myString);
console.log(myNum);
console.log(myBoolean);
console.log(newString);
console.log(myVar);
console.log(strArr);
console.log(numArr);
console.log(boolArr);
console.log(stringArr);
console.log(numberArr);
console.log(strNumTuple);
console.log(numStrTuple);
console.log(boolNumTuple);
console.log(myNull);
console.log(myVoid);
console.log(myUndefined);